# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions: ["smart", "tables"]

kramdown: 
  input: GFM

# Permalinks
relative_permalinks: false
permalink: news/:title/

# Collections
collections:
- doc

collections:
  doc:
    output: true
    permalink: doc/:path/

# Setup
title:            GDX2D
tagline:          'A gaming library'
description:      'A gaming library for the <a href="http://inf1.begincoding.net" target="_blank">INF1 course</a>.'
url:              http://hevs-isi.github.io/gdx2d/
baseurl:          /gdx2d

author:
  name:           'Pierre-André Mudry'
  url:            https://www.hevs.ch

# Custom vars
version:          1.1.1

github:
  repo:           https://github.com/hevs-isi/gdx2d/
