# Dependencies
markdown:         kramdown

kramdown:
  syntax_highlighter: rouge

gems:
  - jemoji

# Permalinks
permalink: news/:title/

# Collections
collections:
- doc

collections:
  doc:
    output: true
    permalink: doc/:path/

# Setup
title:            GDX2D
tagline:          'A gaming library'
description:      'A gaming library for the <a href="http://inf1.begincoding.net" title="INF1" target="_blank">INF1 course</a>.'
url:              https://hevs-isi.github.io/gdx2d/
baseurl:          /gdx2d

author:
  name:           'Pierre-André Mudry'
  url:            http://www.hevs.ch/isi

# Custom vars

# Latest libGDX version
# The download link is '{{ site.github.repo }}archive/v{{ site.github.latestversion }}.zip'
github:
  latestversion: 1.1.1
  repo:          https://github.com/hevs-isi/gdx2d/
