# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            GDX2D
tagline:          'A gaming library'
description:      'A gaming library for the <a href="http://inf1.begincoding.net" target="_blank">INF1 course</a>.'
url:              "http://hevs-isi.github.io/"
baseurl:          'http://hevs-isi.github.io/gdx2d/'

author:
  name:           'Pierre-André Mudry'
  url:            https://www.hevs.ch

paginate:         5

# Custom vars
version:          1.0.1-gamma

github:
  repo:           https://github.com/hevs-isi/gdx2d/
