package ch.hevs.gdx2d.demos.shaders.advanced

import ch.hevs.gdx2d.components.bitmaps.BitmapImage
import ch.hevs.gdx2d.desktop.PortableApplication
import ch.hevs.gdx2d.lib.GdxGraphics
import ch.hevs.gdx2d.lib.utils.Logger
import com.badlogic.gdx.Gdx
import com.badlogic.gdx.graphics.Pixmap.Format
import com.badlogic.gdx.graphics.glutils.FrameBuffer

/**
 * Demonstrates how to use a shader to postprocess
 * an image generated by the library. The idea is to generate
 * everything you want in a backbuffer (~ a texture)
 * then copy it to the active buffer and then apply a
 * shader to which the texture data is the rendered image.
 *
 * @author Pierre-André Mudry
 * @version 1.0
 */
class DemoPostProcessing : PortableApplication() {
    internal var time = 0f
    internal var shaderEnabled = true

    // Used for off screen rendering
    internal lateinit var fbo: FrameBuffer

    // Standard images used for drawing
    internal lateinit var imageAndroid: BitmapImage
    internal lateinit var imageBackground: BitmapImage

    override fun onInit() {
        this.setTitle("Postprocessing with a shader, mui 2013")
        imageAndroid = BitmapImage("images/Android_PI_48x48.png")
        imageBackground = BitmapImage("images/back1_512.png")
        fbo = FrameBuffer(Format.RGBA8888, this.windowWidth, this.windowHeight, false)
        Logger.log("Click to enable/disable shader")
    }

    override fun onGraphicRender(g: GdxGraphics) {
        if (g.shaderRenderer == null) {
            g.setShader("shader/advanced/postprocessing.fp")
        }

        // Draws some stuff to an offscreen buffer, using normal
        // gdx2d primitives
        fbo.begin()
        g.clear()
        g.drawPicture(256f, 256f, imageBackground)
        g.drawTransformedPicture(256f, 256f, time * 100, 1f, imageAndroid)
        g.drawFPS()
        g.drawSchoolLogo()
        fbo.end()

        // Copy the offscreen buffer to the displayed bufer
        g.shaderRenderer.setTexture(fbo.colorBufferTexture, 0)
        g.shaderRenderer.setUniform("enabled", shaderEnabled)

        time += Gdx.graphics.deltaTime
        g.drawShader(time)
    }

    override fun onClick(x: Int, y: Int, button: Int) {
        super.onClick(x, y, button)
        shaderEnabled = !shaderEnabled
    }

    companion object {

        @JvmStatic
        fun main(args: Array<String>) {
            DemoPostProcessing()
        }
    }
}
