package ch.hevs.gdx2d.demos.shaders.advanced

import ch.hevs.gdx2d.components.bitmaps.BitmapImage
import ch.hevs.gdx2d.desktop.DesktopApplication
import ch.hevs.gdx2d.lib.GdxGraphics
import ch.hevs.gdx2d.lib.utils.Logger
import com.badlogic.gdx.Gdx
import com.badlogic.gdx.graphics.Pixmap.Format
import com.badlogic.gdx.graphics.glutils.FrameBuffer

/**
 * Demonstrates how to use a shader to postprocess an image generated by the
 * library.
 *
 * @author Pierre-André Mudry
 * @version 2.0
 */
class DemoPostProcessing extends DesktopApplication {

  private var time = 0f
  private var shaderEnabled = true

  private var fbo: FrameBuffer = _
  private var imageAndroid: BitmapImage = _
  private var imageBackground: BitmapImage = _

  override def onInit(): Unit = {
    setTitle("Postprocessing with a shader, mui 2013")
    imageAndroid = new BitmapImage("images/Android_PI_48x48.png")
    imageBackground = new BitmapImage("images/back1_512.png")
    fbo = new FrameBuffer(Format.RGBA8888, getWindowWidth, getWindowHeight, false)
    Logger.log("Click to enable/disable shader")
  }

  override def onGraphicRender(g: GdxGraphics): Unit = {
    if (g.getShaderRenderer == null) {
      g.setShader("shader/advanced/postprocessing.fp")
    }

    fbo.begin()
    g.clear()
    g.drawPicture(256f, 256f, imageBackground)
    g.drawTransformedPicture(256f, 256f, time * 100f, 1f, imageAndroid)
    g.drawFPS()
    g.drawSchoolLogo()
    fbo.end()

    g.getShaderRenderer.setTexture(fbo.getColorBufferTexture, 0)
    g.getShaderRenderer.setUniform("enabled", shaderEnabled)

    time += Gdx.graphics.getDeltaTime
    g.drawShader(time)
  }

  override def onClick(x: Int, y: Int, button: Int): Unit = {
    super.onClick(x, y, button)
    shaderEnabled = !shaderEnabled
  }

  override def onDispose(): Unit = {
    super.onDispose()
    fbo.dispose()
    imageAndroid.dispose()
    imageBackground.dispose()
  }
}

object DemoPostProcessing {
  def main(args: Array[String]): Unit = {
    new DemoPostProcessing().launch()
  }
}
