package ch.hevs.gdx2d.demos.shaders.advanced

import ch.hevs.gdx2d.components.bitmaps.BitmapImage
import ch.hevs.gdx2d.desktop.DesktopApplication
import ch.hevs.gdx2d.lib.GdxGraphics
import ch.hevs.gdx2d.lib.utils.Logger
import com.badlogic.gdx.Gdx
import com.badlogic.gdx.graphics.Pixmap.Format
import com.badlogic.gdx.graphics.glutils.FrameBuffer
import com.badlogic.gdx.math.Vector3

/**
 * Demonstrates how to use a shader to postprocess an image generated by the
 * library.
 *
 * @author Pierre-André Mudry
 * @version 2.0
 */
class DemoPerspective extends DesktopApplication {

  private var time = 0f
  private var shaderEnabled = true

  private var fbo: FrameBuffer = _
  private var imageAndroid: BitmapImage = _
  private var imageBackground: BitmapImage = _

  private var cameraFov = (math.Pi / 6.0f).toFloat
  private var cameraAngle = (math.Pi / 10.0f).toFloat
  private var cameraPosition = new Vector3(0.0f, -1.0f, 0.02f)
  private var cameraAxis = new Vector3(1.0f, 0.0f, 0.0f)

  override def onInit(): Unit = {
    setTitle("Postprocessing with a shader, mui 2013")
    imageAndroid = new BitmapImage("images/Android_PI_48x48.png")
    imageBackground = new BitmapImage("images/back1_512.png")
    fbo = new FrameBuffer(Format.RGBA8888, getWindowWidth, getWindowHeight, false)
    Logger.log("Click to enable/disable shader")
  }

  override def onGraphicRender(g: GdxGraphics): Unit = {
    if (g.getShaderRenderer == null) {
      g.setShader("shader/advanced/perspective.fp")
    }

    fbo.begin()
    g.clear()
    g.drawPicture(256f, 256f, imageBackground)
    g.drawTransformedPicture(256f, 256f, time * 100f, 1f, imageAndroid)
    g.drawFPS()
    g.drawSchoolLogo()
    g.sbFlush()
    fbo.end()

    g.getShaderRenderer.setTexture(fbo.getColorBufferTexture, 0)
    g.getShaderRenderer.setUniform("enabled", shaderEnabled)
    g.getShaderRenderer.setUniform("cameraPosition", cameraPosition)
    g.getShaderRenderer.setUniform("cameraAxis", cameraAxis)
    g.getShaderRenderer.setUniform("screenPlanDistance", (0.5 / math.atan(cameraFov / 2.0)).toFloat)
    g.getShaderRenderer.setUniform("cameraAngle", cameraAngle)

    cameraPosition.y *= (1f + 0.1f * Gdx.graphics.getDeltaTime)
    cameraPosition.y -= 0.1f * Gdx.graphics.getDeltaTime
    cameraPosition.z *= (1f + 0.05f * Gdx.graphics.getDeltaTime)
    cameraPosition.z += 0.05f * Gdx.graphics.getDeltaTime
    cameraAngle += 0.01f * Gdx.graphics.getDeltaTime

    time += Gdx.graphics.getDeltaTime
    g.drawShader(time)
  }

  override def onClick(x: Int, y: Int, button: Int): Unit = {
    super.onClick(x, y, button)
    shaderEnabled = !shaderEnabled
  }

  override def onDispose(): Unit = {
    super.onDispose()
    fbo.dispose()
    imageAndroid.dispose()
    imageBackground.dispose()
  }
}

object DemoPerspective {
  def main(args: Array[String]): Unit = {
    new DemoPerspective().launch()
  }
}
