package ch.hevs.gdx2d.demos.tilemap

import ch.hevs.gdx2d.desktop.DesktopApplication
import ch.hevs.gdx2d.lib.GdxGraphics
import com.badlogic.gdx.Gdx
import com.badlogic.gdx.Input
import com.badlogic.gdx.maps.tiled.TiledMap
import com.badlogic.gdx.maps.tiled.TiledMapRenderer
import com.badlogic.gdx.maps.tiled.TmxMapLoader
import com.badlogic.gdx.maps.tiled.renderers.OrthogonalTiledMapRenderer
import com.badlogic.gdx.math.Vector2

/**
 * How to load .tmx resources generated by the Tiled editor (http://www.mapeditor.org/)
 *
 * @author Pierre-André Mudry (mui)
 * @version 2.0
 */
class DemoTile extends DesktopApplication {

  private var tiledMap: TiledMap = _
  private var tiledMapRenderer: TiledMapRenderer = _

  private var zoomFactor = 1f
  private var position = new Vector2(0f, 0f)

  override def onInit(): Unit = {
    setTitle("Tile maps loader, mui 2015")
    Gdx.app.log("[TileDemo]", "Demonstrates loading a generated map")

    tiledMap = new TmxMapLoader().load("maps/desert.tmx")
    tiledMapRenderer = new OrthogonalTiledMapRenderer(tiledMap)
  }

  override def onGraphicRender(g: GdxGraphics): Unit = {
    g.clear()
    g.zoom(zoomFactor)
    g.moveCamera(position.x, position.y)

    tiledMapRenderer.setView(g.getCamera)
    tiledMapRenderer.render()

    g.drawSchoolLogo()
    g.drawFPS()
  }

  override def onScroll(amount: Int): Unit = {
    super.onScroll(amount)
    if (amount > 0) zoomFactor += 0.1f
    else zoomFactor -= 0.1f
  }

  override def onKeyDown(keycode: Int): Unit = {
    super.onKeyDown(keycode)
    keycode match {
      case Input.Keys.UP    => position.add(0f, -32f)
      case Input.Keys.DOWN  => position.add(0f, 32f)
      case Input.Keys.LEFT  => position.add(32f, 0f)
      case Input.Keys.RIGHT => position.add(-32f, 0f)
      case _ => ()
    }
  }

  override def onDispose(): Unit = {
    super.onDispose()
    tiledMap.dispose()
  }
}

object DemoTile {
  def main(args: Array[String]): Unit = {
    new DemoTile().launch()
  }
}
